import { StateGraph, StateSchema, START,END,type GraphNode } from "@langchain/langgraph";
import { geminiAiModel, mistralAiModel, cohereAiModel } from "./model.ai.js";
import { createAgent, providerStrategy, HumanMessage } from "langchain";
import z from "zod";

const state = new StateSchema({
  problem: z.string().default(" "),
  solution_1: z.string().default(" "),
  solution_2: z.string().default(" "),
  judge: z.object({
    solution_1_Score: z.number(),
    solution_2_Score: z.number(),
    solution_1_Reasoning: z.string(),
    solution_2_Reasoning: z.string(),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistraResponse, cohereResponse] = await Promise.all([
    mistralAiModel.invoke(state.problem),
    cohereAiModel.invoke(state.problem),
  ]);
  return {
    solution_1: mistraResponse.text,
    solution_2: cohereResponse.text,
  };
};

const judgeNode: GraphNode<typeof state> = async () => {
const {problem, solution_1, solution_2}  = state;

  const judge = createAgent({
    model: geminiAiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_Score: z.number().min(0).max(10),
        solution_2_Score: z.number().min(0).max(10),
        solution_1_Reasoning: z.string(),
        solution_2_Reasoning: z.string(),
      }),
    ),

    systemPrompt: `You are judge tasked with evaluating two solutions generated by different AI models. please provide a score out of 10 for each solution based on their effectiveness in solving the problem, and provide reasoning for the scores you assign. `,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
        problem : ${problem}
        solution 1 : ${solution_1}
        solution 2 : ${solution_2}
        please evaluate the two solutions and provide scores and reasoning.
        `),
    ],
  });

  const {
    solution_1_Score,
    solution_2_Score,
    solution_1_Reasoning,
    solution_2_Reasoning,
  } = judgeResponse.structuredResponse;

  return {
    judge:{
        solution_1_Score,
        solution_2_Score,
        solution_1_Reasoning,
        solution_2_Reasoning,
    }
  }
};


const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge")
    .addEdge("judge", END)
    .compile();


export default graph;